### ISSUE TITLE
Allow for exchange types besides topic

### ISSUE THREAD

**Issue by Bandes** [alphasights/sneakers_handlers#22]
We want to use something like this with a fanout exchange, but it seems that this solution only works with a topic exchange (topic looks like it's hardcoded) - could this be adapted to allow for other types of exchanges, and to respect the config option for exchange type?

**Comment by brianstorti** [comment]
Hey, @Bandes, sorry it took so long to answer, I somehow missed this issue. We just shipped a [change](https://github.com/alphasights/sneakers_handlers/pull/25) that allow us to use the `RetryHandler` and the `DeadLetterHandler` with fanout exchanges.
